export const students = [
  {
    id: 0,
    email: "jaypalsinhrana33333@gmail.com",
    name: "Jaypalsinh Rana",
    type: "2nd",
    isActive: true,
  },
  {
    id: 1,
    email: "parthpatel06072004@gmail.com",
    name: "Parth Hitesh Patel",
    type: "participant",
    isActive: true,
  },
  {
    id: 2,
    email: "sonimehil7@gmail.com",
    name: "Mehil Chapaneri ",
    type: "participant",
    isActive: true,
  },
  {
    id: 3,
    email: "bansigadhvi1410@gmail.com",
    name: "Gadhvi Bansi Mayurdan ",
    type: "participant",
    isActive: true,
  },
  {
    id: 4,
    email: "rajveerjaiswal2909@gmail.com",
    name: "Rajveer Jaiswal Prakash ",
    type: "participant",
    isActive: true,
  },
  {
    id: 5,
    email: "dimplemakwana219@gmail.com",
    name: "Makwana Dimple Ganpatbhai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 6,
    email: "bhavikabhavi188@gmail.com",
    name: "Gehani Bhavika Dineshkumar",
    type: "participant",
    isActive: true,
  },
  {
    id: 7,
    email: "parthvaishnav372@gmail.com",
    name: "Vaishnav Parth Chiragbhai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 8,
    email: "bhavikabhavi188@gmail.com",
    name: "Bhavika Gehani Dinesh Kumar ",
    type: "participant",
    isActive: true,
  },
  {
    id: 9,
    email: "tanvifaladu2004@gmail.com",
    name: "Faladu Tanvi Dahyalal ",
    type: "participant",
    isActive: true,
  },
  {
    id: 10,
    email: "bhavyaaes@gmail.com",
    name: "Bhavya C Patel",
    type: "participant",
    isActive: true,
  },
  {
    id: 11,
    email: "mo.kaif2196@gmail.com",
    name: "Ansari mohammed kaif junedurrehman",
    type: "participant",
    isActive: true,
  },
  {
    id: 12,
    email: "ghodawalaaman@gmail.com",
    name: "Ghodawala Aman",
    type: "participant",
    isActive: true,
  },
  {
    id: 13,
    email: "yashvipalkhiwala2401@gmail.com",
    name: "Yashvi Palkhiwala",
    type: "participant",
    isActive: true,
  },
  {
    id: 14,
    email: "sanskrutidhanani78@gmail.com",
    name: "Sanskruti Dhanani ",
    type: "participant",
    isActive: true,
  },
  {
    id: 15,
    email: "anusha.jotwani@gmail.com",
    name: "Anusha Jotwani ",
    type: "participant",
    isActive: true,
  },
  {
    id: 16,
    email: "shahsiddh08@gmail.com",
    name: "Siddh Divyesh Shah",
    type: "participant",
    isActive: true,
  },
  {
    id: 17,
    email: "7986.stkairdin@gmail.com",
    name: "Riya Gupta ",
    type: "participant",
    isActive: true,
  },
  {
    id: 18,
    email: "devanshi.parikh.j@gmail.com",
    name: "Devanshi Parikh",
    type: "participant",
    isActive: true,
  },
  {
    id: 19,
    email: "shubhamdp.255@gmail.com",
    name: "Shubham prajapati ",
    type: "participant",
    isActive: true,
  },
  {
    id: 20,
    email: "neeraja0093@gmail.com",
    name: "Neeraja Buch",
    type: "participant",
    isActive: true,
  },
  {
    id: 21,
    email: "falgunitagadkar@gmail.com",
    name: "Falguni Tagadkar",
    type: "participant",
    isActive: true,
  },
  {
    id: 22,
    email: "nakshimshah@gmail.com",
    name: "Nakshi Milan Shah",
    type: "participant",
    isActive: true,
  },
  {
    id: 23,
    email: "bhagyashah5122002@gmail.com",
    name: "Bhagya shah ",
    type: "participant",
    isActive: true,
  },
  {
    id: 24,
    email: "rushabh12576@gmail.com",
    name: "Keval Rushabh Sanghvi ",
    type: "participant",
    isActive: true,
  },
  {
    id: 25,
    email: "shahkavi02@gmail.com",
    name: "Shah Kavisha Nipulbhai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 26,
    email: "shahkunj2003@gmail.com",
    name: "Shah kunj Rajeshbhai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 27,
    email: "rishiami254@gmail.com",
    name: "Ami Rishi Riteshkumar",
    type: "participant",
    isActive: true,
  },
  {
    id: 28,
    email: "palpatel1302@gmail.com",
    name: "Pal Patel",
    type: "participant",
    isActive: true,
  },
  {
    id: 29,
    email: "krisharajyaguru84@gmail.com",
    name: "Rajyaguru krisha manishbhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 30,
    email: "luckyprajapati28022004@gmail.com",
    name: "Prajapati Lucky Hasmukhbhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 31,
    email: "drishtithakkar2203@gmail.com",
    name: "Drishti Thakkar",
    type: "participant",
    isActive: true,
  },
  {
    id: 32,
    email: "akshatchoksi8@gmail.com",
    name: "Akshat Aadeshbhai Choksi ",
    type: "participant",
    isActive: true,
  },
  {
    id: 33,
    email: "2021002171210134@ljku.edu.in",
    name: "Meshwa Mitulbhai Prajapati",
    type: "participant",
    isActive: true,
  },
  {
    id: 34,
    email: "prathamnagar3004@gmail.com",
    name: "Nagar Pratham Jaykrushnabhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 35,
    email: "niharshah132004@gmail.com",
    name: "Nihar Shah",
    type: "participant",
    isActive: true,
  },
  {
    id: 36,
    email: "nairajdoctor@gmail.com",
    name: "Naira Doctor ",
    type: "participant",
    isActive: true,
  },
  {
    id: 37,
    email: "2021002170310002@ljku.edu.in",
    name: "fariha chamdawala ",
    type: "participant",
    isActive: true,
  },
  {
    id: 38,
    email: "manasmehta1911@gmail.com",
    name: "Mehta Manas Samir ",
    type: "participant",
    isActive: true,
  },
  {
    id: 39,
    email: "dhruv5gohel@gmail.com",
    name: "Dhruvkumar Gohel",
    type: "participant",
    isActive: true,
  },
  {
    id: 40,
    email: "devanshujethva3000@gmail.com",
    name: "Devanshu D. Jethva",
    type: "3rd",
    isActive: true,
  },
  {
    id: 41,
    email: "2021002171210129@ljku.edu.in",
    name: "Patel vidhi mukeshkumar ",
    type: "participant",
    isActive: true,
  },
  {
    id: 42,
    email: "patelhetvi487@gmail.com",
    name: "Patel Hetvi Nimesh ",
    type: "participant",
    isActive: true,
  },
  {
    id: 43,
    email: "akshatchoksi8@gmail.com",
    name: "Akshat Aadeshbhai choksi",
    type: "participant",
    isActive: true,
  },
  {
    id: 44,
    email: "prathamnagar3004@gmail.com",
    name: "Nagar Pratham Jaykrushnabhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 45,
    email: "bhagyashah5122002@gmail.com",
    name: "Bhagya shah ",
    type: "participant",
    isActive: true,
  },
  {
    id: 46,
    email: "avp346710@gmail.com",
    name: "Ansh V Panchal",
    type: "participant",
    isActive: true,
  },
  {
    id: 47,
    email: "dmrj2003@gmail.com",
    name: "Deep Mehta",
    type: "participant",
    isActive: true,
  },
  {
    id: 48,
    email: "sakshi.raval01@gmail.com",
    name: "Sakshi Raval",
    type: "participant",
    isActive: true,
  },
  {
    id: 49,
    email: "mishvakhamar@gmail.com",
    name: "Mishva piyushkumar khamar ",
    type: "participant",
    isActive: true,
  },
  {
    id: 50,
    email: "uttamraddiya12112003@gmail.com",
    name: "Radadiya Uttam Anilbhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 51,
    email: "jasmeetsarin@gmail.com",
    name: "Jasmeet Sarin",
    type: "participant",
    isActive: true,
  },
  {
    id: 52,
    email: "190320116056.it.vyom.sagar@gmail.com",
    name: "Vyom Sagar ",
    type: "participant",
    isActive: true,
  },
  {
    id: 53,
    email: "pkalawadia123@gmail.com",
    name: "Sachin Kalawadia",
    type: "participant",
    isActive: true,
  },
  {
    id: 54,
    email: "2021002170110017@ljku.edu.in",
    name: "Dabhi Himansu ",
    type: "participant",
    isActive: true,
  },
  {
    id: 55,
    email: "vishwabhadoria2004@gmail.com",
    name: "Vishwa Satendrasingh Bhadoria ",
    type: "participant",
    isActive: true,
  },
  {
    id: 56,
    email: "mrkanasagara@gmail.com",
    name: "Kanasagara Meet Rajubhai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 57,
    email: "het.sojitra4399@gmail.com",
    name: "Sojitra Het ",
    type: "participant",
    isActive: true,
  },
  {
    id: 58,
    email: "abhishekmakwana7021@gmnail.com",
    name: "Makwana Abhishek Rameshbhai",
    type: "participant",
    isActive: true,
  },
  {
    id: 59,
    email: "pruthulpatel01@gmail.com",
    name: "Pruthul Patel",
    type: "1st",
    isActive: true,
  },
  {
    id: 60,
    email: "yeshashah9825@gmail.com",
    name: "Yesha Shah",
    type: "participant",
    isActive: true,
  },
  {
    id: 61,
    email: "pateldevarsh718@gmail.com",
    name: "Devarsh Jigneshkumar Patel",
    type: "participant",
    isActive: true,
  },
  {
    id: 62,
    email: "vedant26200007@gmail.com",
    name: "Vedant Thakkar",
    type: "participant",
    isActive: true,
  },
  {
    id: 63,
    email: "radhikadesai583@gmail.com",
    name: "Radhika Desai ",
    type: "participant",
    isActive: true,
  },
  {
    id: 64,
    email: "laramak2509@gmail.com",
    name: "Lara Makwana ",
    type: "participant",
    isActive: true,
  },
  {
    id: 65,
    email: "kotharirishi0@gmail.com",
    name: "Kothari Rishi Dinesh",
    type: "participant",
    isActive: true,
  },
  {
    id: 66,
    email: "2021002170210103@ljku.edu.in",
    name: "Zazwala Shehnazbegum Saidahemad ",
    type: "participant",
    isActive: true,
  },
  {
    id: 67,
    email: "shahnaman004@gmail.com",
    name: "Shah Naman",
    type: "participant",
    isActive: true,
  },
  {
    id: 68,
    email: "pragatiukani@gmail.com",
    name: "Pragati Ukani",
    type: "participant",
    isActive: true,
  },
  {
    id: 69,
    email: "hinalsolanki1107@gmail.com",
    name: "Hiral Solanki",
    type: "participant",
    isActive: true,
  },
  {
    id: 70,
    email: "prinsapatel0203@gmail.com",
    name: "Prinsha Patel",
    type: "participant",
    isActive: true,
  },
  /* MENTORS */
  {
    id: 71,
    email: "",
    name: "Dhrumin Mittal",
    type: "mentor",
    isActive: true,
  },
  {
    id: 72,
    email: "",
    name: "Eshika Jagani",
    type: "mentor",
    isActive: true,
  },
  {
    id: 73,
    email: "",
    name: "Kriyanshi Shah",
    type: "mentor",
    isActive: true,
  },
  {
    id: 74,
    email: "",
    name: "Shivam Tripathi",
    type: "mentor",
    isActive: true,
  },
  /* Co-Ordinators */
  {
    id: 75,
    email: "",
    name: "Fagun Doshi",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 76,
    email: "",
    name: "Ishan Pathak",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 77,
    email: "",
    name: "Aarjav Panchal",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 78,
    email: "",
    name: "Vivek Thobani",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 79,
    email: "",
    name: "Kaiwal Panchal",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 80,
    email: "",
    name: "Sujal Luhar ",
    type: "co-ordinator",
    isActive: true,
  },
  {
    id: 81,
    email: "",
    name: "Devanshu Shah",
    type: "co-ordinator",
    isActive: true,
  },
];